### ISSUE TITLE
task id is known during test?

### ISSUE THREAD

**Issue by rumusan** [JosephKJ/ELI#1]

**Comment by JosephKJ** [comment]
Task id is not required, but we need to know whether the test instance belongs to the last-learned task or not (note that this is a much weaker requirement when compared to task aware methods). We have explained this in Sec 3.2.2. We can side-step this by learning a simple binary classifier to do the discrimination.

**Comment by rumusan** [comment]
thank you! and could you tell me the position of the code for it? 
btw, did the binary classifier not suffer from the class imbalance problem (rehearsal data vs. new data) in experiments?

**Comment by JosephKJ** [comment]
Hi, I think you got me wrongly. ELI doesn't have the binary classifier, but that can be one way to get around the weak requirement that we have. We will explore this in a future work.

**Comment by rumusan** [comment]
the current results are obtained with information  (belongs to the last-learned task or not)  of test data?

**Comment by JosephKJ** [comment]
Yes.

**Comment by rumusan** [comment]
test information is known, feature are aligned to old model, then predict with old classifier. 
why not just use last-learned model to predict old tasks and new model to predict new task.
