### ISSUE TITLE
How to obtain the test results?

### ISSUE THREAD

**Issue by AmingWu** [JosephKJ/ELI#2]
I have run your code successfully. But I do not know how to see the test results. Could you give me some advice?

Thank you.

**Comment by JosephKJ** [comment]
You can read the last few lines in the log. Hope you are using the provided scripts as is.

**Comment by AmingWu** [comment]
Thank you. This is my log. However, I find the results are very low. I directly perform run.sh
![QQ截图20220418075730](https://user-images.githubusercontent.com/38445175/163737092-6666566a-dbb3-4577-bf65-298cbf6e634a.png)
.

**Comment by JosephKJ** [comment]
Please share your complete logs so that we can debug. I wonder whether the base models are loaded properly. Thanks.

**Comment by AmingWu** [comment]
[log.txt](https://github.com/JosephKJ/ELI/files/8502851/log.txt)

This is my log

**Comment by JosephKJ** [comment]
`./output/10_p_10_ft/model_final.pth` is not being loaded. This is evident from the lines "[04/17 11:57:02] d2.evaluation.pascal_voc_evaluation". Can you please share `ls ./output/10_p_10_ft`?

Also, please find my log for your reference: 
[log.txt](https://github.com/JosephKJ/ELI/files/8502900/log.txt)

**Comment by AmingWu** [comment]
Thanks. I do not change your code. Could you give me some advice to reproduce your results?

**Comment by AmingWu** [comment]
Is your run.sh correct?

**Comment by JosephKJ** [comment]
Yes, it is correct. Please respond to my question: Can you please share "ls ./output/10_p_10_ft".

Have you downloaded and extracted the models as explained in the third point [here](https://github.com/JosephKJ/ELI/blob/main/detection/README.md#installation-and-setup)?

**Comment by AmingWu** [comment]
Yes. I have downloaded the models. I observe that your code needs to use these models.
![QQ截图20220418101651](https://user-images.githubusercontent.com/38445175/163744136-525df2fb-0878-4683-939a-55d91172cf33.png)

**Comment by JosephKJ** [comment]
1. What is your version of fvcore? 

2. Also, do you see any errors while the code loads the models? These errors may appear only on the screen, it might not necessarily be logged to file.

3. Can you show the contents inside 10_p_10_ft?

**Comment by AmingWu** [comment]
The version of fvcore is 0.1.1.dev200512

**Comment by AmingWu** [comment]
The 10_p_10_ft is the same as my download. It does not change.
![QQ截图20220418102713](https://user-images.githubusercontent.com/38445175/163744915-97add5e3-0c24-4e91-9403-3dd95c721131.png)

**Comment by JosephKJ** [comment]
Thanks for sharing these. As I mentioned before, the issues is in loading the model parameters. That is why the accuracies are very low (you can do a side-by-side comparison to my logs). 

I wonder whether it is a file permission issue. Instead of creating shortcuts, can you copy paste the contents from the extracted models into "output" folder? Also, is there any extra message that comes up in the standard system-output when the following log comes: "fvcore.common.checkpoint INFO: Loading checkpoint from"

(I am bit busy during the day, will get back later.)

**Comment by JosephKJ** [comment]
Hello, please reopen this incase your issue is not yet resolved. https://github.com/JosephKJ/ELI/issues/6 might have been the reason.
