### ISSUE TITLE
code url of OW-DETR is wrong

### ISSUE THREAD

**Issue by shuangshuangguo** [JosephKJ/ELI#3]
![image](https://user-images.githubusercontent.com/31126075/163961850-1a11dc9c-62a8-4565-8ab7-d37086f81001.png)
The Code URL is wrong with 404 bug. Can you share the correct url, please?

**Comment by salman-h-khan** [comment]
The code link is now corrected: https://github.com/akshitac8/OW-DETR

**Comment by shuangshuangguo** [comment]
Thank you very much!
