### ISSUE TITLE
How can I get "./base_50.pt"?

### ISSUE THREAD

**Issue by zhangziyi1670** [JosephKJ/ELI#7]
![image](https://user-images.githubusercontent.com/75550266/189508745-fce1246e-ff48-4e49-b238-be4d6965925e.png)
In the classfication/main.py,there is a parameter named ckpt_dir_fg in line26，the default value of it was ./base_50.pt. How
 can I get this file?

**Comment by windbro98** [comment]
So can you please share how to get the "./base_50.pt"? I face the same problem too.

**Comment by zhangziyi1670** [comment]
> 

you can choose to delete the --resume_fg and --resume_with_ebm_training in the .sh file and then the model will be trained from the begin.

**Comment by JosephKJ** [comment]
You are correct @zhangziyi1670. Thanks for your contribution!

**Comment by windbro98** [comment]
@zhangziyi1670 Thanks for your help!
